DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS DEPARTMENT;
DROP TABLE IF EXISTS EMPLOYEE2;
DROP TABLE IF EXISTS DEPARTMENT2;

CREATE TABLE DEPARTMENT (
  ID IDENTITY PRIMARY KEY,
  NAME VARCHAR(64) NOT NULL
);

CREATE TABLE EMPLOYEE (
  ID IDENTITY PRIMARY KEY,
  NAME VARCHAR(64) NOT NULL,
  DEPT_ID LONG,
  CONSTRAINT FK_EMP_DEPT_ID FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENT(ID)
);

CREATE TABLE DEPARTMENT2 (
  ID IDENTITY PRIMARY KEY,
  NAME VARCHAR(64) NOT NULL
);

CREATE TABLE EMPLOYEE2 (
  ID IDENTITY PRIMARY KEY,
  NAME VARCHAR(64) NOT NULL,
  DEPT_ID LONG,
  CONSTRAINT FK_EMP_DEPT2_ID FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENT2(ID)
);
